name: Test Electron Build

on:
  push:
    branches:
      - test-ci
  pull_request:
    branches:
      - test-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}  # 使用 matrix 中的 os 配置来指定 macos-11 或 macos-12

    strategy:
      matrix:
        platform: [win, linux]       # Windows 和 Linux 平台
        os: [macos-11, macos-12]     # macOS 的两种版本
        include:
          - platform: mac            # 为 macOS 设置单独的构建步骤
            os: macos-11
          - platform: mac
            os: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and Python environment
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install frontend dependencies and build # vue 构建
        run: |
          pnpm install
          pnpm run build-only
        working-directory: ./frontend

      - name: Install backend Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Build Python backend for ${{ matrix.platform }}
        run: |
          python pyi_auto_pack_ci.py ${{ matrix.platform }}
        working-directory: ./backend

      - name: Build Electron app for ${{ matrix.platform }}
        run: |
          echo "Building Electron app for ${{ matrix.platform }} on ${{ matrix.os }}"
          if [ "${{ matrix.platform }}" == "win" ]; then
            pnpm run electron-builder --win
          elif [ "${{ matrix.platform }}" == "mac" ]; then
            if [ "${{ matrix.os }}" == "macos-11" ]; then
              pnpm run electron-builder --mac --x64  # 针对 x86_64
            elif [ "${{ matrix.os }}" == "macos-12" ]; then
              pnpm run electron-builder --mac --arm64  # 针对 arm64
            fi
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            pnpm run electron-builder --linux
          fi
        working-directory: ./frontend

      - name: Upload build artifacts for ${{ matrix.platform }} on ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.platform }}-${{ matrix.os }}
          path: build/${{ matrix.platform }}/*
